[advisories]
vulnerability = "deny"
# cargo-deny ≥0.18 expects a target set for `unmaintained` (one of
# "all", "workspace", "transitive", or "none"). Using "workspace" scopes
# the check to this workspace and fixes the v0.18 config schema error.
unmaintained = "workspace"
yanked = "warn"
unsound = "deny"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "Unicode-3.0",
  "MPL-2.0",
  "Unicode-DFS-2016"
]
deny = [
  "AGPL-3.0",
  "GPL-3.0",
  "LGPL-3.0"
]
allow-osi-fsf-free = "either"
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
